import { z } from "zod";
import { AppObjectKey } from "@/lib/app-objects-schemas";
import {
  Mail,
  User,
  Briefcase,
  Users,
  Building2,
  Building,
  FileText,
  Target,
  Package,
  TrendingUp,
  Receipt,
  Calendar,
  StickyNote,
  File,
  Megaphone,
  FolderOpen,
  Video,
  Truck,
  CreditCard,
  Folder,
  MessageSquare,
  FileMinus,
  HardDrive,
  Clock,
  UserCheck,
  DollarSign,
  BookOpen,
  Shield,
  Database,
  BarChart3,
  List,
  Award,
  Percent,
} from "lucide-react";
import {
  UserRecord,
  OrderRecord,
  JobApplicationRecord,
  ContactRecord,
  JobRecord,
  CompanyRecord,
  JobCandidateRecord,
  TaskRecord,
  ProductRecord,
  LeadRecord,
  DealRecord,
  InvoiceRecord,
  ActivityRecord,
  NoteRecord,
  CustomerRecord,
  EmployeeRecord,
  CampaignRecord,
  ProjectRecord,
  MeetingRecord,
  SupplierRecord,
  PaymentRecord,
  FolderRecord,
  DocumentRecord,
  MessageRecord,
  BillRecord,
  CreditNoteRecord,
  DriveRecord,
  DriveItemRecord,
  TimeoffBalanceRecord,
  TimeoffRequestRecord,
  DealStageRecord,
  CampaignMemberRecord,
  DealProductRecord,
  PayrollRecord,
  EeocRecord,
  ContactListRecord,
  JobInterviewRecord,
  JournalEntryRecord,
  JobOfferRecord,
  TaxRateRecord,
  LedgerAccountRecord,
} from "@/components/object";
import { IRecord } from "../models/types";
import {
  ordersSchema,
  usersSchema,
  jobapplicationsSchema,
  contactsSchema,
  jobsSchema,
  companiesSchema,
  jobcandidatesSchema,
  tasksSchema,
  productsSchema,
  leadsSchema,
  dealsSchema,
  invoicesSchema,
  activitiesSchema,
  notesSchema,
  emailsSchema,
  filesSchema,
  customersSchema,
  employeesSchema,
  campaignsSchema,
  projectsSchema,
  meetingsSchema,
  suppliersSchema,
  paymentsSchema,
  foldersSchema,
  documentsSchema,
  messagesSchema,
  billsSchema,
  creditnotesSchema,
  drivesSchema,
  driveitemsSchema,
  timeoffbalancesSchema,
  timeoffrequestsSchema,
  dealstagesSchema,
  campaignmembersSchema,
  dealproductsSchema,
  payrollsSchema,
  eeocsSchema,
  contactlistsSchema,
  jobinterviewsSchema,
  journalentriesSchema,
  joboffersSchema,
  taxratesSchema,
  ledgeraccountsSchema,
} from "./app-objects-schemas";
import { EmailRecord } from "@/components/object/email-record";
import { FileRecord } from "@/components/object/file-record";

interface AppObject {
  /**
   * The schema for the object on this app
   */
  schema: z.ZodObject<z.ZodRawShape>;

  /**
   * Wether users are allowed to delete this object type
   */
  allowDelete: boolean;

  /**
   * Wether users are allowed to update this object type
   */
  allowUpdate: boolean;

  /**
   * Wether users are allowed to create this object type
   */
  allowCreate: boolean;

  /**
   * Icon for this object type
   */
  icon: React.ComponentType<{ className?: string }>;

  /**
   * Component for rendering this object type
   */
  component: React.ComponentType<{ record: IRecord }>;

  /**
   * Readable name for the object
   */
  label: string;

  /**
   * Category for grouping object types
   */
  category?: string;
}

export interface CategoryIcon {
  icon: React.ComponentType<{ className?: string }>;
  label: string;
}

export const categoryIcons: Record<string, CategoryIcon> = {
  CRM: {
    icon: Users,
    label: "Customer Relationship Management",
  },
  Recruitment: {
    icon: Briefcase,
    label: "Recruitment & HR",
  },
  Finance: {
    icon: DollarSign,
    label: "Finance & Accounting",
  },
  Documents: {
    icon: FileText,
    label: "Documents & Files",
  },
  Others: {
    icon: List,
    label: "Other Objects",
  },
};

const appObjects: Record<AppObjectKey, AppObject> = {
  orders: {
    label: "Order",
    schema: ordersSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: Mail,
    component: OrderRecord,
    category: "Finance",
  },
  users: {
    label: "User",
    schema: usersSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: User,
    component: UserRecord,
  },
  "job-applications": {
    label: "Job Application",
    schema: jobapplicationsSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: Briefcase,
    component: JobApplicationRecord,
    category: "Recruitment",
  },
  contacts: {
    label: "Contact",
    schema: contactsSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: Users,
    component: ContactRecord,
    category: "CRM",
  },
  jobs: {
    label: "Job",
    schema: jobsSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: Building2,
    component: JobRecord,
    category: "Recruitment",
  },
  companies: {
    label: "Company",
    schema: companiesSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: Building,
    component: CompanyRecord,
    category: "CRM",
  },
  "job-candidates": {
    label: "Job Candidates",
    schema: jobcandidatesSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: FileText,
    component: JobCandidateRecord,
    category: "Recruitment",
  },
  tasks: {
    label: "Task",
    schema: tasksSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: Target,
    component: TaskRecord,
    category: "CRM",
  },
  products: {
    label: "Product",
    schema: productsSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: Package,
    component: ProductRecord,
  },
  leads: {
    label: "Lead",
    schema: leadsSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: TrendingUp,
    component: LeadRecord,
    category: "CRM",
  },
  deals: {
    label: "Deal",
    schema: dealsSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: TrendingUp,
    component: DealRecord,
    category: "CRM",
  },
  invoices: {
    label: "Invoice",
    schema: invoicesSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: Receipt,
    component: InvoiceRecord,
    category: "Finance",
  },
  activities: {
    label: "Activity",
    schema: activitiesSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: Calendar,
    component: ActivityRecord,
    category: "CRM",
  },
  notes: {
    label: "Note",
    schema: notesSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: StickyNote,
    component: NoteRecord,
    category: "Documents",
  },
  emails: {
    label: "Email",
    schema: emailsSchema,
    allowDelete: true,
    allowUpdate: false,
    allowCreate: true,
    icon: Mail,
    component: EmailRecord,
    category: "Documents",
  },
  files: {
    label: "File",
    schema: filesSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: File,
    component: FileRecord,
    category: "Documents",
  },
  customers: {
    label: "Customer",
    schema: customersSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: Building2,
    component: CustomerRecord,
    category: "CRM",
  },
  employees: {
    label: "Employee",
    schema: employeesSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: User,
    component: EmployeeRecord,
  },
  campaigns: {
    label: "Campaign",
    schema: campaignsSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: Megaphone,
    component: CampaignRecord,
    category: "CRM",
  },
  projects: {
    label: "Project",
    schema: projectsSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: FolderOpen,
    component: ProjectRecord,
  },
  meetings: {
    label: "Meeting",
    schema: meetingsSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: Video,
    component: MeetingRecord,
    category: "CRM",
  },
  suppliers: {
    label: "Supplier",
    schema: suppliersSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: Truck,
    component: SupplierRecord,
  },
  payments: {
    label: "Payment",
    schema: paymentsSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: CreditCard,
    component: PaymentRecord,
    category: "Finance",
  },
  folders: {
    label: "Folder",
    schema: foldersSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: Folder,
    component: FolderRecord,
    category: "Documents",
  },
  documents: {
    label: "Document",
    schema: documentsSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: FileText,
    component: DocumentRecord,
    category: "Documents",
  },
  messages: {
    label: "Message",
    schema: messagesSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: MessageSquare,
    component: MessageRecord,
    category: "Documents",
  },
  bills: {
    label: "Bill",
    schema: billsSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: Receipt,
    component: BillRecord,
    category: "Finance",
  },
  "credit-notes": {
    label: "Credit Note",
    schema: creditnotesSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: FileMinus,
    component: CreditNoteRecord,
    category: "Finance",
  },
  drives: {
    label: "Drive",
    schema: drivesSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: HardDrive,
    component: DriveRecord,
    category: "Documents",
  },
  "drive-items": {
    label: "Drive Item",
    schema: driveitemsSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: File,
    component: DriveItemRecord,
    category: "Documents",
  },
  "timeoff-balances": {
    label: "Timeoff Balance",
    schema: timeoffbalancesSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: Clock,
    component: TimeoffBalanceRecord,
  },
  "timeoff-requests": {
    label: "Timeoff Request",
    schema: timeoffrequestsSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: Calendar,
    component: TimeoffRequestRecord,
  },
  "deal-stages": {
    label: "Deal Stage",
    schema: dealstagesSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: BarChart3,
    component: DealStageRecord,
    category: "CRM",
  },
  "campaign-members": {
    label: "Campaign Member",
    schema: campaignmembersSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: Users,
    component: CampaignMemberRecord,
    category: "CRM",
  },
  "deal-products": {
    label: "Deal Product",
    schema: dealproductsSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: Package,
    component: DealProductRecord,
    category: "CRM",
  },
  payrolls: {
    label: "Payroll",
    schema: payrollsSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: DollarSign,
    component: PayrollRecord,
    category: "Finance",
  },
  eeocs: {
    label: "EEOC",
    schema: eeocsSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: Shield,
    component: EeocRecord,
  },
  "contact-lists": {
    label: "Contact List",
    schema: contactlistsSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: List,
    component: ContactListRecord,
    category: "CRM",
  },
  "job-interviews": {
    label: "Job Interview",
    schema: jobinterviewsSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: UserCheck,
    component: JobInterviewRecord,
    category: "Recruitment",
  },
  "journal-entries": {
    label: "Journal Entry",
    schema: journalentriesSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: BookOpen,
    component: JournalEntryRecord,
    category: "Finance",
  },
  "job-offers": {
    label: "Job Offer",
    schema: joboffersSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: Award,
    component: JobOfferRecord,
    category: "Recruitment",
  },
  "tax-rates": {
    label: "Tax Rate",
    schema: taxratesSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: Percent,
    component: TaxRateRecord,
    category: "Finance",
  },
  "ledger-accounts": {
    label: "Ledger Account",
    schema: ledgeraccountsSchema,
    allowDelete: true,
    allowUpdate: true,
    allowCreate: true,
    icon: Database,
    component: LedgerAccountRecord,
    category: "Finance",
  },
};

export default appObjects;
